In [21]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
display(a)
# TD: array from 1 to 6 (done)

a = np.array([[1, 2], [3, 4]])
display(a)
print(f'a[1]: {a[1]}')
# TD: identity matrix


array([1, 2, 3, 4, 5, 6])

array([[1, 2],
       [3, 4]])

a[1]: [3 4]


**ndarray** = n-dimensional array<br>
**ndarray** class represents vectors and matrices<br>
**tensor** is an usual term for +3 dimensions

In [65]:
display(np.zeros(2))
display(np.ones(3))
display(np.ones((1, 2)))

display(np.empty(2))

display(np.arange(4))
display(np.arange(2, 8))
display(np.arange(16, 2, -2.))

display(np.linspace(1, 5, num=5))
display(
    [f'5 x {i} = {int(num)}' 
        for i, num in enumerate(
            np.linspace(5, 50, num=10), start=1
        )
    ]
)

array([0., 0.])

array([1., 1., 1.])

array([[1., 1.]])

array([1., 1.])

array([0, 1, 2, 3])

array([2, 3, 4, 5, 6, 7])

array([16., 14., 12., 10.,  8.,  6.,  4.])

array([1., 2., 3., 4., 5.])

['5 x 1 = 5',
 '5 x 2 = 10',
 '5 x 3 = 15',
 '5 x 4 = 20',
 '5 x 5 = 25',
 '5 x 6 = 30',
 '5 x 7 = 35',
 '5 x 8 = 40',
 '5 x 9 = 45',
 '5 x 10 = 50']

In [76]:
display(
    np.array([1, 2, 3, 4, 5]) 
    +
    np.array([4, 2, 0, -2, -4])
)

display(np.array([0.5, 1, 1.5, 2, 2.5]) * 2)

array([5, 4, 3, 2, 1])

array([1., 2., 3., 4., 5.])

In [95]:
a = np.array([1, 3, 2, 5, 4, 7, 6])
display(np.sort(a))
display(a)
display(np.argsort(a))
display(np.partition(a, 2))
display(np.partition(a, (2, 4)))


array([1, 2, 3, 4, 5, 6, 7])

array([1, 3, 2, 5, 4, 7, 6])

array([0, 2, 1, 4, 3, 6, 5])

array([1, 2, 3, 5, 4, 7, 6])

array([1, 2, 3, 4, 5, 7, 6])